export const UPDATE_USER_MUTATION = 'UPDATE_USER_MUTATION'
export const UPDATE_TOKEN_MUTATION = 'UPDATE_TOKEN_MUTATION'
export const UPDATE_SEARCH_MUTATION = 'UPDATE_SEARCH_MUTATION'
export const UPDATE_CENTER_PAPERS_MUTATION = 'UPDATE_CENTER_PAPERS_MUTATION'